language: java
jdk:
  - oraclejdk11
  - openjdk11

cache:
  directories:
    - .autoconf
    - $HOME/.m2

services:
  - postgresql

before_script:
  - psql -c "create user pismo with password 'pismo';" -U postgres
  - psql -c 'create database pismo;' -U postgres